apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
  namespace: dev
  labels:
    app: welcome-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - name: welcome-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: welcome-page
          mountPath: /usr/share/nginx/html
      volumes:
      - name: welcome-page
        configMap:
          name: welcome-page-config

